/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as abstracts from "./abstracts";
export type { abstracts };
import type * as test from "./test";
export type { test };
export type { TenXBank } from "./TenXBank";
